### ISSUE TITLE
Magic number

### ISSUE THREAD

**Issue by SusTaras** [IlyaDanilenko/PyArinst#2]
https://github.com/IlyaDanilenko/pyarinst/blob/0d70b3daaa436a01ef29c47f604f117d04b1c49a/pyarinst/pyarinst.py#L96

10700000 - can you explain what this number stands for?
I believe this is intermediateFrequency, but why is it hardcoded?

**Comment by IlyaDanilenko** [comment]
You're right. This number is the intermediate frequency. However, the description of the [protocol](http://arinst.ru/download-apk.php) says that this value, although it depends on the hardware specific, should be kept at 10700000.

**Comment by SusTaras** [comment]
Thanks for the response!
